# Generated by Django 3.2.9 on 2021-12-07 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20211207_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='deviceid',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_id',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='patient_device',
            name='deviceid',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='patient_device',
            name='patient_id',
            field=models.CharField(max_length=20),
        ),
    ]
