# Generated by Django 3.2.9 on 2021-12-09 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_alter_patient_patient_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='add_time',
            field=models.CharField(default='2021-12-09 19:52:01', max_length=20),
        ),
        migrations.AddField(
            model_name='patient',
            name='add_time',
            field=models.CharField(default='2021-12-09 19:52:01', max_length=20),
        ),
        migrations.AddField(
            model_name='patient_device',
            name='bind_time',
            field=models.CharField(default='2021-12-09 19:52:01', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='add_time',
            field=models.CharField(default='2021-12-09 19:52:01', max_length=20),
        ),
    ]
